### ISSUE TITLE
Add support for testing of Relay enabled components

### ISSUE THREAD

**Issue by adamkl** [brysgo/create-react-app#20]
### Is this a bug report?

Yes

### Steps to Reproduce

(Write your steps here:)

1. Create a unit test that calls a component that contains a graphql tagged template literal
2. run `yarn test`

### Expected Behavior

Unit test passes

### Actual Behavior

```sh
 FAIL  src\App\App.test.js
  ● Test suite failed to run

    Invariant Violation: graphql: Unexpected invocation at runtime. Either the Babel transform was not set up, or it failed to identify this call site.
 Make sure it is being used verbatim as `graphql`.

      at invariant (node_modules/fbjs/lib/invariant.js:42:15)
      at Object.graphql (node_modules/relay-runtime/lib/RelayModernGraphQLTag.js:22:32)
      at Object.<anonymous> (src/Benefit/CalcRow.js:19:20)
      at Object.<anonymous> (src/Benefit/Benefit.js:3:16)
      at Object.<anonymous> (src/Benefit/index.js:1:180)
      at Object.<anonymous> (src/BenefitPage.js:4:16)
      at Object.<anonymous> (src/App/App.js:15:329)
      at Object.<anonymous> (src/App/App.test.js:3:12)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by adamkl** [comment]
I'm guessing that babel isn't transpiling the tagged templates before jest runs the tests.

**Comment by brysgo** [comment]
Aww, I thought I fixed that one. I'll take a look.

**Comment by brysgo** [comment]
^^ That is the probably cause of the problem, I will test and deploy when I find some more time.

**Comment by brysgo** [comment]
@adamkl - I just published an update that works over here, let me know if it still doesn't work.

**Comment by brysgo** [comment]
I'm closing the Adam, because I tested it on the project you were trying it on and the tests pass. Let me know if you have any other issues!

**Comment by brysgo** [comment]
I can't get the tests to pass now for some reason.

**Comment by brysgo** [comment]
This is still open because I haven't documented / smoothed it out, but I was able to get tests working.
